# FineTune/Load=True_roberta-base_22_12_2021_12:52_B=16_lr _5e-08_lambda=0.05_temp=0.3
model_params:
    exp_name: FineTune
    model: roberta-base
    classify: True # use head classifier 
   

training_params:
    N: 5 # the numbers of example per class 
    T: 1 # the numbers of trials
    temp: 0.3 # τ ∈ {0.1, 0.3, 0.5}
    batch_size: 16  
    n_epochs: 30
    lamda: 0.05       # λ′∈ {0.01, 0.03, 0.05}
    running_times: 10
    lr: 0.00000005 #5e-8
    device: cuda:1 
    smoothness: 0.7 
    running_times: 10
